services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  node:
    build: 
      context: .
    ports:
      - '3200:3200'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
